apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: data-platform
  namespace: argocd
spec:
  description: Data platform local production-like stack
  sourceRepos:
    - '*'
  destinations:
    - namespace: monitoring
      server: https://kubernetes.default.svc
    - namespace: data-platform
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
