apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: data-platform-loki
  namespace: argocd
spec:
  project: data-platform
  sources:
  - repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 6.20.0
    helm:
      releaseName: loki
      valueFiles:
      - $values/k8s/values-loki-prod.yaml
  - repoURL: https://github.com/LOCAL/REPLACE-ME.git
    targetRevision: HEAD
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true