apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: data-platform-monitoring
  namespace: argocd
spec:
  project: data-platform
  sources:
  - repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 65.8.1
    helm:
      releaseName: kube-prometheus-stack
      valueFiles:
      - $values/k8s/values-kube-prometheus-stack-prod.yaml
  - repoURL: https://github.com/paulchen8206/Data-Platform-Grafana-Prometheus.git
    targetRevision: HEAD
    ref: values
  - repoURL: https://github.com/paulchen8206/Data-Platform-Grafana-Prometheus.git
    targetRevision: HEAD
    path: k8s/observability
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - Replace=true