images:
  zookeeper: confluentinc/cp-zookeeper:7.6.1
  kafka: confluentinc/cp-kafka:7.6.1
  schemaRegistry: confluentinc/cp-schema-registry:7.6.1
  minio: minio/minio:RELEASE.2024-10-29T16-01-48Z
  minioMc: minio/mc:RELEASE.2025-04-16T18-13-26Z
  sparkRuntime: data-platform-grafana-prometheus-spark-runtime:latest
  sparkJob: data-platform-grafana-prometheus-spark-job:latest
  producer: data-platform-grafana-prometheus-producer:latest
  kafkaUi: provectuslabs/kafka-ui:v0.7.2
  kafkaExporter: danielqsj/kafka-exporter:v1.7.0
imagePullPolicy: IfNotPresent
service:
  type: ClusterIP
persistence:
  minioSize: 10Gi
  sparkCheckpointsSize: 2Gi
resources:
  defaultRequests:
    cpu: 100m
    memory: 256Mi
  defaultLimits:
    cpu: 1000m
    memory: 1Gi